# Generated by Django 5.2.6 on 2025-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_hoteluser_is_verified_hotelvendor_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelvendor",
            name="business_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
