# Generated by Django 5.2.1 on 2025-11-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_hotelbookings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelbookings",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="accounts.hotels",
            ),
        ),
    ]
